# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R_evalcast

on:
  push:
    branches: [ main, evalcast ]
  pull_request:
    branches: [ main, evalcast ]

env:
  USE_BSPM: "true"
  _R_CHECK_FORCE_SUGGESTS_: "false"
  R_VERSION: 3.5

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: R-packages/evalcast/

    steps:
      - uses: actions/checkout@v2

      # See https://eddelbuettel.github.io/r-ci/ for more info on below.
      - name: Bootstrap
        run: |
          curl -OLs https://eddelbuettel.github.io/r-ci/run.sh
          chmod 0755 run.sh
          ./run.sh bootstrap

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-eval-1-

      - name: Dependencies
        run: ./run.sh install_all

      - name: Test
        run: ./run.sh run_tests
